### ISSUE TITLE
Sprites with Gear

### ISSUE THREAD

**Issue by thisisbrad** [Tech-Talk-FS/Kaplay-Jam#1]
We need Sprites with weapons. 

- [ ] Three types of characters
- [ ] Three types of weapons
- [ ] animations of each stance

You will need to make one sprite sheet for each player and weapon.  The player should be "rigged" up in Kaplay.

**Comment by IrwinJames-FS** [comment]
Are we still doing three different characters or one where we focus on general behavior?
